name: Push components to https://components.espressif.com
on:
  push:
     branches:
       - master
jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: "recursive"

      - name: Upload components to the component registry
        uses: espressif/github-actions/upload_components@master
        with:
          name: arduino-esp32
          namespace: espressif
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
          service_url: ${{ secrets.IDF_COMPONENT_API_URL }}
